import createClient from "openapi-fetch";

// In a real codebase this would import the generated `paths` type from
// `src/generated/openapi.ts` — generated by `npm run openapi`. We fall back
// to `unknown` here so the template builds without running the backend.
type Paths = Record<string, unknown>;

export const client = createClient<Paths>({ baseUrl: "" });
